# Generated by Django 3.1.5 on 2021-05-30 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210530_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
